# Workflow для сборки и деплоя сайта на Hugo на GitHub Pages
name: Deploy Hugo site to GitHub Pages

on:
  # Запуск при пушах в основную ветку
  push:
    branches: [$default-branch]

  # Запуск вручную через Actions
  workflow_dispatch:

# Настройка разрешений GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Контроль одновременных запусков
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Работа по сборке сайта
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: |
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Работа по деплою
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
